### ISSUE TITLE
"Enablement" block no longer has design

### ISSUE THREAD

**Issue by scottbuscemi** [pantheon-systems/documentation#9019]
Re: [Caching: Advanced Topics](https://docs.pantheon.io/caching-advanced-topics)

Priority: Low/Medium/High (choose one, remove the other options)

## Issue Description:

"Enablement" block no longer has specific formatting so it looks out of place.

## Suggested Resolution

**Comment by stevector** [comment]
@scottbuscemi I'm not sure which block you're referring to. But it might have been solved with https://github.com/pantheon-systems/documentation/issues/8815 and https://github.com/pantheon-systems/documentation/pull/9074

Can you check?

**Comment by scottbuscemi** [comment]
<img width="1050" alt="Screenshot 2024-07-10 at 3 48 34 PM" src="https://github.com/pantheon-systems/documentation/assets/4336848/5e9b5526-388e-499a-b43f-b70186f01bda">
This isn't resolved. The `<Enablement>` block has no formatting so it seems like a random header/paragraph in the middle of a doc.

**Comment by stevector** [comment]
Ah, I understand now. @mel-miller I don't know that we need a separate `Enablement` React component in addition to the `Alert` React component.

The `Enablement` component does not include anything the from `pds`: https://github.com/pantheon-systems/documentation/blob/main/src/components/enablement/index.js

The `Alert` component does. https://github.com/pantheon-systems/documentation/blob/main/src/components/alert/index.js


I think the appropriate resolution here is for me to make a PR that either
1. Deletes the `Enablement` component and replaces all usages with the `Alert` component and sets the type to `info`.
2. Updates the `Enablement` component to use the `Callout` component from `pds` and hard codes the type to `info`.

I think option 2 is better as it will make it easier to preserver the analytics tracking present in the `Enablement` component now. Though I should double check that anyone is is checking those analytics.

**Comment by stevector** [comment]
@rachelwhitton since you're working more closely with a design system update right now, can you take this issue?
